### ISSUE TITLE
Release versioning

### ISSUE THREAD

**Issue by rtuin** [xtrasmal/TacticianBundle#22]
Just noticed this repo doesn't have any releases yet. I guess we should start making them.

Is it OK if I (or someone else) creates a 0.1? And go from there?

**Comment by rdohms** [comment]
I was just waiting for the PR i just opened to suggest we tag a initial release.
I agree with `0.1.0`

**Comment by rtuin** [comment]
Yeah would be good to get that one in the first release. Let's wait for #21

**Comment by rosstuck** [comment]
With #21, we've also added tests and multiple command bus support. Maybe it's time to bring it to the League? @xtrasmal: thoughts?

**Comment by rdohms** [comment]
I'm +1 on moving it, the sooner we do it the sooner i can update my project to something stable-r :P

**Comment by xtrasmal** [comment]
@rosstuck Yes please. I see the issues coming by, but I can't find time to gather my thoughts and respond most of the time lately.

**Comment by rosstuck** [comment]
Okay, I'll talk to the League and get things moving ASAP.

**Comment by rtuin** [comment]
Would be a nice move!

**Comment by rosstuck** [comment]
Done: https://github.com/thephpleague/tactician-bundle

I've setup the CI etc, @rdohms is gonna move the namespace.

@xtrasmal Can you use the deprecation feature on Packagist to redirect folks to the new bundle on Packagist? :smile: 

Feel free to keep sending in PRs and issues, I'm too swamped to actively develop right now but will try my damndest to review and merge in short order. Thanks again for all of your dynamite work here, fellas. :)

**Comment by xtrasmal** [comment]
:D super cool.

**Comment by rtuin** [comment]
Very nice! You're not alone on this one as you know @rosstuck..

**Comment by xtrasmal** [comment]
Ok packagist redirect is in place.
