### ISSUE TITLE
Bump to Tactician 0.4

### ISSUE THREAD

**Issue by rosstuck** [xtrasmal/TacticianBundle#8]
I released a new version of Tactician yesterday which removes the Command interface, so any POPO can now be a command.

To upgrade, we need to do some rework here: specifically removing the Command typehint everywhere (substituting object for it) and changing a couple of the mocks in the tests.

I'm a bit swamped and might not get to it for a day or two. Any takers? :sweat_smile:

**Comment by rosstuck** [comment]
Actually, let's wait for the upcoming 0.5 in the next couple days, it will make one other change by splitting an interface.

**Comment by xtrasmal** [comment]
ok tell us when it's ready

**Comment by rosstuck** [comment]
Done!
