### ISSUE TITLE
Travis + Scrutinizer setup

### ISSUE THREAD

**Issue by rosstuck** [xtrasmal/TacticianBundle#9]
While we're doing dev work, it'd be nice to have Travis working as well. We can do that here or consider moving over to a League repo in the near future. :)

**Comment by xtrasmal** [comment]
I've just connected to Travis, but haven't done anyting like that before. That never stopped me before, but because of the "being swamped" thing.. any advice would be nice.  @rdohms perhaps?

**Comment by rosstuck** [comment]
@xtrasmal You only need to connect to Travis and add a .travis.yml file, you can probably crib the one from Tactician itself.

That said, if it sounds like a hassle and you'd still like to see this go to the league, I can transfer it to a League repo tomorrow and setup Travis, Scrutinizier, Packagist, etc in one go. :)

**Comment by xtrasmal** [comment]
@rosstuck in the end it will go to the league anyways, so if you are happy with the quality of the Bundle, then we should do that. So very exited!

**Comment by xtrasmal** [comment]
@rosstuck We have a greenlight Travis CI. Just realised that Tactician is >5.5

**Comment by rosstuck** [comment]
Awesome! The main migration point for me is the unit tests and maybe multiple command bus support (since that'll break tests). If we've got those in place, long term maintenance becomes much easier to commit to under the League. :)

**Comment by rdohms** [comment]
@rosstuck tests, check. Let's work on the Multiple Bus issue to nail down the goal so we can see about implementing.

**Comment by rosstuck** [comment]
Cool, lemme know your thoughts on #6

**Comment by rdohms** [comment]
@rosstuck already did, waiting for your reply at #6 :P
